### ISSUE TITLE
Change of parent in animation - not supported

### ISSUE THREAD

**Issue by wojtossfm** [wojtossfm/godot_scml_importer#10]
There are cases where between animations items may move between parents. This is currently not supported and needs work.

Broken out of #7

**Comment by wojtossfm** [comment]
I see two possible solutions:
 * use remote transforms (creating one for each possible location where the item ends up) when we detect multiple parents and have the animations set/unset the remote path depending on the animation. The actual branch that has multiple potential parents would need to be in the base layer of the skeleton
 *  use a custom function call triggered in the animation that moves the actual branch between parents if required

**Comment by fabiodellaria** [comment]
Thank you for your efforts.

**Comment by wojtossfm** [comment]
I believe this should now be supported by having the references on different parents be separate instances. Untested how well it works with blending but this generally isn't a feature I would encourage people to use but wanted at least some basic support for now. Can explore different solutions in the future if needed.

Reparenting the object through function calls seemed to generally work but was confusing since it didn't present nicely in previews and so opted to not include it for now.
