### ISSUE TITLE
Does not work with Godot 4.0

### ISSUE THREAD

**Issue by dadoftwins** [wojtossfm/godot_scml_importer#18]
I'm just trying this out with Godot 4.0 and it doesn't work.  I get syntax errors as well as api usage errors.

Thanks for this btw!  Looking forward to trying it out if it ends up working on 4.0.

**Comment by wojtossfm** [comment]
@dadoftwins 0.8.0 should now work with Godot 4.0.stable. Feel free to re-open if it doesn't work for you though if you encounter a different issue please raise it separately. I've submitted a new asset entry to Godot [assets](https://godotengine.org/asset-library/asset) so when that gets approved it should also appear there.
