### ISSUE TITLE
No Bone2D children of node bone. Cannot calculate bone length or angle reliably.   Using transform rotation for bone angle

### ISSUE THREAD

**Issue by Abab-bk** [wojtossfm/godot_scml_importer#26]
It has no effect on the running of the game, but the error reporting is annoying.
![image](https://github.com/wojtossfm/godot_scml_importer/assets/55276676/36bafd19-1f55-49b3-bcaf-eeea1f030d8a)

**Comment by wojtossfm** [comment]
Resolved with https://github.com/wojtossfm/godot_scml_importer/pull/33
