### ISSUE TITLE
SCML is not loaded properly.

### ISSUE THREAD

**Issue by oddman621** [wojtossfm/godot_scml_importer#28]
OS: Windows 11 x64
Godot version: 4.1 stable
addon version: 0.9.0, [0.9.1](https://github.com/wojtossfm/godot_scml_importer/tree/27-importing-issues)

Example Project: 
[scml_test_4_1.zip](https://github.com/wojtossfm/godot_scml_importer/files/13953524/scml_test_4_1.zip)

Description:
 1. Add SCML importer addon.
 2. Copy and paste a Spriter Pro project folder into godot project folder.
 3. Enable SCML importer addon.
 4. See some error messages.
![image](https://github.com/wojtossfm/godot_scml_importer/assets/15917089/383247b1-174b-4d04-804b-def4890e3bd3)
 5. Open scml file by double-click.
 6. Scml file opened, but not properly. (missing "hopper/idle", only "impacts/impact1" but not loaded properly either)

**Comment by oddman621** [comment]
That version is better, but still has problems.

The environment is same, Windows 11 x64, Godot 4.1 stable.

I resaved SCML file of spriter project and tried with this: 
[scml_test_4_1_scml_resaved.zip](https://github.com/wojtossfm/godot_scml_importer/files/14020706/scml_test_4_1_scml_resaved.zip)

 1. A lot of errors appeared when copying a Spriter project folder to the Godot project folder.
<img width="1493" alt="2manyerr" src="https://github.com/wojtossfm/godot_scml_importer/assets/15917089/c89ddcc1-84f3-465a-9633-6adf530d937c">

 2.  All of nodes of SCML scene has zero scale. When I scale up one of the nodes, It scales but nothing drawn.

 3.  On SCML scene, when I move the mouse pointer on editor's viewport, bunch of error message floods. Look at the black arrow at the bottom right of the video below.

https://github.com/wojtossfm/godot_scml_importer/assets/15917089/1fff3404-73ca-4812-b62f-308ff01704ef

**Comment by oddman621** [comment]
I added the original Spriter project I'm using just in case you need it.

[getting_started.zip](https://github.com/wojtossfm/godot_scml_importer/files/14020826/getting_started.zip)

**Comment by wojtossfm** [comment]
Hm. I cannot quite pinpoint where they are coming from but after loading up the project and doing a re-import on the scml I don't get any errors so I think they might be in some way transient and the plugin not working as intended while the import is still happening but might be working fine after the import is fully done? It might end up being a form of race condition. Could you confirm you are seeing the same? I would want to try to judge how big of an issue it is.

**Comment by wojtossfm** [comment]
Closing as I believe the overall main issue is resolved and I haven't heard back.
