### ISSUE TITLE
I cannot find the "Import SCML" button

### ISSUE THREAD

**Issue by fabiodellaria** [wojtossfm/godot_scml_importer#3]
I cannot find the "Import SCML" button, can you make a little tutorial, please?

Thanks.

**Comment by wojtossfm** [comment]
I'll try to put something together for you but if you are using 0.7 then it is an import plugin and you just open an scml file in godot. E.g. if you have a directory with the images and a scml file then put the directory into your godot project and open the scml file in the filesystem dock. Make sure you enabled the plugin too.

**Comment by wojtossfm** [comment]
I believe the issue here was the Readme being misleading. I've updated in #5
