### ISSUE TITLE
Importing Bug

### ISSUE THREAD

**Issue by fabiodellaria** [wojtossfm/godot_scml_importer#4]
Trying to import the following project, generate wrong scene

https://drive.google.com/file/d/1XdxASfW5ILD8Yxi_M3aJfb3R_c45V96E/view?usp=sharing

**Comment by wojtossfm** [comment]
I believe I've spotted the problem. Can you try the version from the branch referenced above (
6a5a013). It worked for me with the project you shared. You will need to adjust the animation player speed to your liking (10 seemed to look fairly like what was in Spriter Pro).

**Comment by wojtossfm** [comment]
@fabiodellaria I've raised #6 and #7 for the other issues I've spotted that will be affecting your 2nd bug report. Please watch them appropriately for updates.

**Comment by fabiodellaria** [comment]
OK, thank you

Il giorno ven 5 feb 2021 alle ore 10:57 Wojciech Michalak <
notifications@github.com> ha scritto:
